name: Add or Update translation
description: To add or update translation for description of this script
labels: ["translation"]
body:
  - type: textarea
    id: language-translation
    attributes:
      label: Language
      placeholder: "Enter language"
      description: "Language into which the translation is made"
    validations:
      required: true

  - type: textarea
    id: readme-translation
    attributes:
      label: README.md
      placeholder: "Enter translation"
      description: "Translation for README.md"
    validations:
      required: true

  - type: textarea
    id: name-translation
    attributes:
      label: Script name
      placeholder: "Enter translation"
      description: "Translation for name of the script"
    validations:
      required: true

  - type: textarea
    id: description-translation
    attributes:
      label: Script short description
      placeholder: "Enter translation"
      description: "Translation for the script's short description"
    validations:
      required: true
