name: Question about script
description: To ask a question about this script
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: "Enter your question about this script"
    validations:
      required: true
